### PR TITLE
Add Storyteller and PayPal for Kelly

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Might as well add myself and add more options for copleykj.

### CODE REVIEW

**Comment by harryadel** [comment]
How can I say no to a fellow Meteor Developer? :sweat_smile: Thank you, @StorytellerCZ !

**Comment by harryadel** [comment]
I was so excited, I forgot to properly review the PR. :smile:

**Comment by StorytellerCZ** [comment]
:laughing: :tada: ありがとう

**Comment by harryadel** [comment]
Screenshot_2019-10-11 Google Translate

Your welcome! :smile:

**Pull request merged**
